# Generated by Django 6.0.7 on 2026-07-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='logo',
        ),
        migrations.AddField(
            model_name='university',
            name='province',
            field=models.CharField(default='Punjab', max_length=100),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_type', models.CharField(choices=[('BS', 'Bachelor of Science'), ('BBA', 'Bachelor of Business Administration'), ('MBA', 'Master of Business Administration'), ('MS', 'Master of Science'), ('PHD', 'Doctor of Philosophy')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('study_system', models.CharField(choices=[('SEMESTER', 'Semester'), ('TRIMESTER', 'Trimester'), ('ANNUAL', 'Annual')], default='SEMESTER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academic.university')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['university', 'degree_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('university', 'degree_type', 'name'), name='unique_program_per_university')],
            },
        ),
    ]
