# Generated by Django 6.0.7 on 2026-07-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_remove_university_logo_university_province_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['university', 'degree_type', 'program_name'], 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.RemoveConstraint(
            model_name='program',
            name='unique_program_per_university',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='program_name',
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('university', 'degree_type', 'program_name'), name='unique_program_per_university'),
        ),
    ]
