# Generated by Django 6.0.7 on 2026-07-11 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(max_length=20)),
                ('recommended_semester', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('theory_credit_hours', models.PositiveSmallIntegerField()),
                ('lab_credit_hours', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('UNIVERSITY', 'University Requirement'), ('GENERAL', 'General Education')], default='CORE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_courses', to='academic.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_courses', to='academic.program')),
            ],
            options={
                'verbose_name': 'Program Course',
                'verbose_name_plural': 'Program Courses',
                'ordering': ['program', 'recommended_semester', 'course_code'],
                'constraints': [models.UniqueConstraint(fields=('program', 'course'), name='unique_course_per_program'), models.UniqueConstraint(fields=('program', 'course_code'), name='unique_course_code_per_program')],
            },
        ),
    ]
