# Generated by Django 6.0.7 on 2026-07-19 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_academicsession_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programcourse',
            name='course_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Course code must look like CS101, CSC-201, MTH101, SE301 etc.', regex='^[A-Za-z]{2,6}-?\\d{2,4}[A-Za-z]?$')]),
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('repeat_policy', models.CharField(choices=[('LATEST_ATTEMPT', 'Latest Attempt'), ('HIGHEST_GRADE', 'Highest Grade'), ('ALL_ATTEMPTS', 'All Attempts')], default='LATEST_ATTEMPT', max_length=30)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_schemes', to='academic.university')),
            ],
            options={
                'verbose_name': 'Grading Scheme',
                'verbose_name_plural': 'Grading Schemes',
                'ordering': ('-effective_from',),
            },
        ),
        migrations.CreateModel(
            name='GradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('grade_points', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('minimum_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grading_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_points', to='academic.gradingscheme')),
            ],
            options={
                'verbose_name': 'Grade Point',
                'verbose_name_plural': 'Grade Points',
                'ordering': ('-grade_points',),
                'constraints': [models.UniqueConstraint(fields=('grading_scheme', 'grade'), name='unique_grade_per_scheme')],
            },
        ),
    ]
