# Generated by Django 6.0.7 on 2026-07-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_alter_programcourse_course_code_gradingscheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradingscheme',
            name='name',
        ),
    ]
