# Generated by Django 6.0.7 on 2026-07-23 12:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_remove_gradingscheme_name'),
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='extracted_text',
            field=models.TextField(blank=True, editable=False, help_text='Text pulled from the uploaded file at save time. Used only for search; never returned by the API.'),
        ),
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, help_text='Postgres full-text search index, kept in sync via NoteService.', null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='note_search_vector_idx'),
        ),
    ]
