# Generated by Django 6.0.7 on 2026-07-11 12:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0008_alter_academicsession_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_graduation_date', models.DateField()),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_BREAK', 'On Break'), ('GRADUATED', 'Graduated'), ('DROPPED', 'Dropped')], default='ACTIVE', max_length=20)),
                ('joined_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.academicsession')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.program')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.university')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['university', 'program', 'user'],
            },
        ),
    ]
