# Generated by Django 6.0.7 on 2026-07-11 17:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_academicsession_year'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_taken', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn'), ('INCOMPLETE', 'Incomplete')], default='ENROLLED', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=2, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('remarks', models.TextField(blank=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_courses', to='academic.academicsession')),
                ('program_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_courses', to='academic.programcourse')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-academic_session', 'semester_taken'],
            },
        ),
    ]
